backend:
  name: github
  repo: Jayku1201/sibi1029
branch: postgres-support
medmedia_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "home"
    label: "Home"
    files:
      - file: "content/home.json"
        label: "Home"
        name: "home"
