name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish container
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma client
        run: npm run prisma:generate

      - name: Build application
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Notify deployment target
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: needs.build-and-publish.result == 'success'
    steps:
      - name: Deployment instructions
        run: |
          echo "Image published: ghcr.io/${{ github.repository }}"
          echo "Trigger your infrastructure deployment (e.g., Render, Fly.io) using this image."
